/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KnjigaIzlaz;

import Db.KnjigaIzlazDAO;
import Util.HelpClass;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Home
 */
public class KnjigaIzlazGUI extends javax.swing.JDialog {

    private void filter(String query) {

        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>((DefaultTableModel) jTablePrikazKnjigaIzlaz.getModel());
        jTablePrikazKnjigaIzlaz.setRowSorter(trs);

        trs.setRowFilter(RowFilter.regexFilter("(?i)" + query));

    }

    public KnjigaIzlazGUI(java.awt.Frame parent, boolean modal) throws SQLException, IOException, ClassNotFoundException {
        super(parent, modal);
        initComponents();

        KnjigaIzlazDAO db = new KnjigaIzlazDAO();
        db.fillTableKI(jTablePrikazKnjigaIzlaz);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrikazKnjigaIzlaz = new javax.swing.JTable();
        btn_novi_unos = new javax.swing.JButton();
        jlblPretraga = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jbtnExport = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTablePrikazKnjigaIzlaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Redni broj", "Primalac", "Opis", "Datum slanja", "Količina", "Vrsta", "Poslao", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePrikazKnjigaIzlaz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTablePrikazKnjigaIzlazFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrikazKnjigaIzlaz);
        if (jTablePrikazKnjigaIzlaz.getColumnModel().getColumnCount() > 0) {
            jTablePrikazKnjigaIzlaz.getColumnModel().getColumn(7).setPreferredWidth(0);
        }

        btn_novi_unos.setText("Novi unos");
        btn_novi_unos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novi_unosActionPerformed(evt);
            }
        });

        jlblPretraga.setText("Pretraga");

        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        jtfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSearchKeyReleased(evt);
            }
        });

        jbtnExport.setText("Export to xls");
        jbtnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExportActionPerformed(evt);
            }
        });

        btnExportPDF.setText("Export to PDF");
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_novi_unos)
                        .addGap(100, 100, 100)
                        .addComponent(jlblPretraga)
                        .addGap(18, 18, 18)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(91, 91, 91)
                        .addComponent(btnExportPDF)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnExport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novi_unos)
                    .addComponent(jlblPretraga)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExport)
                    .addComponent(btnExportPDF)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novi_unosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novi_unosActionPerformed
        try {
            JDialog dialog = new UnosKnjigaIzlazGUI(new javax.swing.JFrame(), rootPaneCheckingEnabled);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(KnjigaIzlazGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_novi_unosActionPerformed

    private void jTablePrikazKnjigaIzlazFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTablePrikazKnjigaIzlazFocusGained

    }//GEN-LAST:event_jTablePrikazKnjigaIzlazFocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained


    }//GEN-LAST:event_formFocusGained

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formHierarchyChanged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
//        try {
//            KnjigaUlazDAO db = new KnjigaUlazDAO();
//            db.fillTableKU(jTablePrikazKnjigaUlaz);
//        } catch (SQLException ex) {
//            Logger.getLogger(KnjigaUlazGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jtfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSearchKeyReleased
        String query = jtfSearch.getText().toLowerCase();
        filter(query);

    }//GEN-LAST:event_jtfSearchKeyReleased


    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed

    }//GEN-LAST:event_jtfSearchActionPerformed

    private void jbtnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExportActionPerformed

        try {
            HelpClass.Writer(jTablePrikazKnjigaIzlaz);
            // System.out.println("export done");
        } catch (IOException ex) {
            Logger.getLogger(KnjigaIzlazGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnExportActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed

        MessageFormat header = new MessageFormat("Knjiga ulaz");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");

        try {
            jTablePrikazKnjigaIzlaz.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(KnjigaIzlazGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {
            int row = jTablePrikazKnjigaIzlaz.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "Odaberite red za edit");
                return;
            }

            JDialog dialog = new EditKnjigaIzlazGUI(new javax.swing.JFrame(), rootPaneCheckingEnabled);

            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(KnjigaIzlazGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnjigaIzlazGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    KnjigaIzlazGUI dialog = new KnjigaIzlazGUI(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException e) {
                    System.out.println(e);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(KnjigaIzlazGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btn_novi_unos;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTablePrikazKnjigaIzlaz;
    private javax.swing.JButton jbtnExport;
    private javax.swing.JLabel jlblPretraga;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables
}
