/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.KnjigaUlaz;

import Db.KnjigaUlazDAO;
import Db.OrgJediniceDAO;
import Util.HelpClass;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.KnjigaUlaz;
import model.OrgJedinice;

/**
 *
 * @author Home
 */
public class UnosKnjigaUlazGUI extends javax.swing.JDialog {

    /**
     * Creates new form UnosKnjigaIzlazGUI
     *
     * @param parent
     * @param modal
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     */
    public UnosKnjigaUlazGUI(java.awt.Frame parent, boolean modal) throws IOException, ClassNotFoundException {
        super(parent, modal);
        initComponents();

        OrgJediniceDAO datab = new OrgJediniceDAO();
        List<OrgJedinice> list;
        list = datab.getAllOrgJed();
       
        comboOrgJedinica.setModel(new DefaultComboBoxModel(list.toArray()));
        tfPodbroj.requestFocus();
        String datum = HelpClass.localDateFormatter(LocalDate.now());
        tfDatumPrijema.setText(datum);
        KnjigaUlazDAO db = new KnjigaUlazDAO();

        tfOsnovniBroj.setText(String.valueOf(db.maxOsnovniBrojKU() + 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOsnovniBroj = new javax.swing.JLabel();
        lblOpis = new javax.swing.JLabel();
        lblPodbroj = new javax.swing.JLabel();
        lblDatumPrijema = new javax.swing.JLabel();
        lblPosiljalac = new javax.swing.JLabel();
        lblBrojAkta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfOsnovniBroj = new javax.swing.JTextField();
        tfPodbroj = new javax.swing.JTextField();
        tfPosiljalac = new javax.swing.JTextField();
        tfBrojAkta = new javax.swing.JTextField();
        comboOrgJedinica = new javax.swing.JComboBox<>();
        btnSnimi = new javax.swing.JButton();
        tfOpis = new javax.swing.JTextField();
        tfDatumPrijema = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblOsnovniBroj.setText("Osnovni broj");

        lblOpis.setText("Opis");

        lblPodbroj.setText("Podbroj");

        lblDatumPrijema.setText("Datum prijema");

        lblPosiljalac.setText("Pošiljalac");

        lblBrojAkta.setText("Broj akta");

        jLabel1.setText("Org. jedinica");

        tfOsnovniBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOsnovniBrojActionPerformed(evt);
            }
        });

        tfPodbroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPodbrojActionPerformed(evt);
            }
        });

        comboOrgJedinica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Racunovodsvo", "Item 2", "Item 3", "Item 4" }));

        btnSnimi.setText("Snimi");
        btnSnimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnimiActionPerformed(evt);
            }
        });

        tfOpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOpisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumPrijema, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPodbroj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPosiljalac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrojAkta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOsnovniBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSnimi)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboOrgJedinica, 0, 242, Short.MAX_VALUE)
                                    .addComponent(tfBrojAkta)
                                    .addComponent(tfPosiljalac)
                                    .addComponent(tfPodbroj)
                                    .addComponent(tfDatumPrijema)
                                    .addComponent(tfOsnovniBroj)
                                    .addComponent(tfOpis))
                                .addGap(26, 26, 26))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsnovniBroj)
                    .addComponent(tfOsnovniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumPrijema)
                    .addComponent(tfDatumPrijema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPodbroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPodbroj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpis)
                    .addComponent(tfOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosiljalac)
                    .addComponent(tfPosiljalac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrojAkta)
                    .addComponent(tfBrojAkta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboOrgJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSnimi)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfOsnovniBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOsnovniBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOsnovniBrojActionPerformed

    private void btnSnimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnimiActionPerformed
        KnjigaUlazDAO db = new KnjigaUlazDAO();

        try {

            if (!HelpClass.isNum(tfOsnovniBroj.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Osnovni broj mora biti cijeli broj!");
                return;
            }

            if (!HelpClass.dateMatcher(tfDatumPrijema.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Datum mora biti u formatu dd.MM.yyyy!");
                return;
            }

            int osnovniBroj = Integer.valueOf(tfOsnovniBroj.getText());
            String opis = tfOpis.getText();
            Date date = HelpClass.stringToDate(tfDatumPrijema.getText());
            String posiljalac = tfPosiljalac.getText();
            String broj_akta = tfBrojAkta.getText();
            String orgJedinica = comboOrgJedinica.getSelectedItem().toString();

            if (tfPodbroj.getText().equals("")) {
                KnjigaUlaz ki = new KnjigaUlaz(osnovniBroj, opis, date, posiljalac, broj_akta, orgJedinica);
                db.insertKU(ki);
            } else {
                if (!HelpClass.isNum(tfPodbroj.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Osnovni broj mora biti cijeli broj!");
                    return;
                }
                int podbroj = Integer.valueOf(tfPodbroj.getText());
                KnjigaUlaz ki = new KnjigaUlaz(osnovniBroj, opis, podbroj, date, posiljalac, broj_akta, orgJedinica);
                db.insertKU(ki);

            }

            db.fillTableKU(KnjigaUlazGUI.jTablePrikazKnjigaUlaz);

        } catch (HeadlessException | NumberFormatException | SQLException | ParseException e) {
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(UnosKnjigaUlazGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        HelpClass.clrFields(tfBrojAkta, tfOpis, tfOsnovniBroj, tfPodbroj, tfPosiljalac);

        String datum = HelpClass.localDateFormatter(LocalDate.now());
        tfDatumPrijema.setText(datum);
        try {
            tfOsnovniBroj.setText(String.valueOf(db.maxOsnovniBrojKU() + 1));
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(UnosKnjigaUlazGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSnimiActionPerformed

    private void tfPodbrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPodbrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPodbrojActionPerformed

    private void tfOpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOpisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosKnjigaUlazGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                UnosKnjigaUlazGUI dialog = new UnosKnjigaUlazGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(UnosKnjigaUlazGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSnimi;
    private javax.swing.JComboBox<String> comboOrgJedinica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBrojAkta;
    private javax.swing.JLabel lblDatumPrijema;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblOsnovniBroj;
    private javax.swing.JLabel lblPodbroj;
    private javax.swing.JLabel lblPosiljalac;
    private javax.swing.JTextField tfBrojAkta;
    private javax.swing.JTextField tfDatumPrijema;
    private javax.swing.JTextField tfOpis;
    private javax.swing.JTextField tfOsnovniBroj;
    private javax.swing.JTextField tfPodbroj;
    private javax.swing.JTextField tfPosiljalac;
    // End of variables declaration//GEN-END:variables
}
